apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8
    ports:
    - containerPort: 3306
    env: 
    - name: "MYSQL_ROOT_PASSWORD"
      value: "test"
    volumeMounts:
    - name: "k8s-mysql-storage"
      mountPath: "/var/lib/mysql"
      volumes:
      - name: "k8s-mysql-storage"
        emptyDir: {}