apiVersion: v1
kind: Service
metadata:
  name: dev-mysql-service
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 33306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql