apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 3306
    nodePort: 32000
    protocol: TCP
  selector:
    app: mysql
